# This is a basic workflow to help you get started with MATLAB Actions

name: SDMX Build and test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-java:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 8 for x64
          uses: actions/setup-java@v3
          with:
            java-version: '8'
            distribution: 'temurin'
            architecture: x64

        - name: Run the Ant jar target
          run: cd JAVA && ant clean && ant compile && ant dist

        - name: Archive MATLAB JAR for next job
          uses: actions/upload-artifact@v3
          with:
            name: SDMX
            path: MATLAB/lib/SDMX.jar
            if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    build-test-matlab:
      needs: build-java
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Download a single artifact
          uses: actions/download-artifact@v3
          with:
            name: SDMX
            path: MATLAB/lib
            
        # Sets up MATLAB on the GitHub Actions runner
        - name: Show jar
          run: MATLAB && ls MATLAB/lib


        
